openapi: 3.1.0
info:
  title: Resizer Service API
  version: 1.0.0
  description: API to generate tasks to resize images asynchronously

paths:
  /tasks:
    post:
      summary: Create a task
      description: Generate a task to resize an image given its local path or an url.
      requestBody:
        description: required information to create the resizing task.
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    url:
                      description: url of the image to download before resizing it.
                      type: string
                      format: uri
                      minLength: 1
                  required:
                    - url
                - type: object
                  properties:
                    path:
                      description: local path to the image. The path is relative to the service, no the host machine.
                      type: string
                      minLength: 1
            examples:
              UrlTask:
                value:
                  url: https://picsum.photos/1920/1080
              PathTask:
                value:
                  path: /output/sample-image.png
      responses:
        '201':
          description: The task was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                PendingTask:
                  value:
                    taskId: b40484f0-adb9-4881-a100-2faa71082766
                    status: pending
                    price: 23.1
                FailedTask:
                  value:
                    taskId: b40484f0-adb9-4881-a100-2faa71082766
                    status: failed
                    price: 23.1
                    error:
                      code: IMG_NOT_FOUND_ERROR
                      message: Could not load the image
                CompletedTask:
                  value:
                    taskId: b40484f0-adb9-4881-a100-2faa71082766
                    status: completed
                    price: 23.1
                    images:
                      - resolution: '1024'
                        path: /output/sample-image/1024/1876902378.png
                      - resolution: '800'
                        path: /output/sample-image/800/23074602836.png

        '422':
          description: The input data is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                ValidationError:
                  value:
                    code: VALIDATION_ERROR
                    message: Invalid input data
                    status: 422
        '500':
          description: There was an unexpected error in the Service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                StorageError:
                  value:
                    code: STORAGE_ERROR
                    message: There was an unexpected error in storage
                    status: 500
  /tasks/{taskId}:
    get:
      summary: Get the state of a Task
      description: Obtain the status of a task by searching it in database.
      parameters:
        - name: taskId
          in: path
          required: true
          description: the identifier of the requested task.
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: The task was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                PendingTask:
                  value:
                    taskId: b40484f0-adb9-4881-a100-2faa71082766
                    status: pending
                    price: 23.1
                FailedTask:
                  value:
                    taskId: b40484f0-adb9-4881-a100-2faa71082766
                    status: failed
                    price: 23.1
                    error:
                      code: IMG_NOT_FOUND_ERROR
                      message: Could not load the image
                CompletedTask:
                  value:
                    taskId: b40484f0-adb9-4881-a100-2faa71082766
                    status: completed
                    price: 23.1
                    images:
                      - resolution: '1024'
                        path: /output/sample-image/1024/1876902378.png
                      - resolution: '800'
                        path: /output/sample-image/800/23074602836.png

        '422':
          description: The input data is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                ValidationError:
                  value:
                    code: VALIDATION_ERROR
                    message: Invalid input data
                    status: 422
        '500':
          description: There was an unexpected error in the Service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                StorageError:
                  value:
                    code: STORAGE_ERROR
                    message: There was an unexpected error in storage
                    status: 500

components:
  schemas:
    ServiceError:
      type: object
      properties:
        code:
          description: identifier of the type of error
          type: string
        message:
          description: human-readable description of the error
          type: string
        status:
          description: http status associated with the error
          type: number
        data:
          description: additional information about the context of the error
          type: object
      required:
        - code
        - message
        - status
    Task:
      type: object
      properties:
        taskId:
          description: identifier of the task, used in searches.
          type: string
          forat: uuid
        status:
          description: indicates whether the task has complete or not, or if it had an error during its execution.
          type: string
          enum:
            - pending
            - completed
            - failed
        price:
          description: an arbitrary price assigned to the task.
          type: number
        images:
          description: list of images created during the processing of this task.
          type: array
          minItems: 1
          items:
            type: object
            properties:
              resolution:
                description: the width of the resulting image after resizing, or 'original' if it is the initial image that was used for the resizing.
                type: string
              path:
                description: local path to the image file, from the perpective of the service, not the host machine.
                type: string
            required:
              - resolution
              - path
        error:
          $ref: '#/components/schemas/ServiceError'
      required:
        - taskId
        - status
        - price
